export const properties = [
  {
    id: 1,
    titulo: "Apartamento Moderno no Centro",
    preco: 450000,
    tipo: "apartamento",
    transacao: "venda",
    cidade: "São Paulo",
    bairro: "Centro",
    quartos: 2,
    banheiros: 2,
    area: 85,
    descricao:
      "Apartamento completamente reformado no coração da cidade. Localização privilegiada com fácil acesso ao transporte público e principais avenidas.",
    caracteristicas: ["Ar condicionado", "Varanda", "Portaria 24h", "Elevador", "Garagem"],
    imagem: "/placeholder.svg?height=300&width=400",
    galeria: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: 2,
    titulo: "Casa com Jardim",
    preco: 2800,
    tipo: "casa",
    transacao: "aluguel",
    cidade: "São Paulo",
    bairro: "Vila Madalena",
    quartos: 3,
    banheiros: 2,
    area: 120,
    descricao:
      "Linda casa com jardim em bairro nobre. Perfeita para famílias que buscam tranquilidade sem abrir mão da proximidade com o centro.",
    caracteristicas: ["Jardim", "Churrasqueira", "Garagem para 2 carros", "Lavanderia", "Quintal"],
    imagem: "/placeholder.svg?height=300&width=400",
    galeria: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: 3,
    titulo: "Loft Industrial",
    preco: 380000,
    tipo: "apartamento",
    transacao: "venda",
    cidade: "São Paulo",
    bairro: "Pinheiros",
    quartos: 1,
    banheiros: 1,
    area: 65,
    descricao: "Loft com design industrial único. Pé direito alto, muito bem iluminado e em excelente localização.",
    caracteristicas: ["Pé direito alto", "Design industrial", "Muito iluminado", "Portaria", "Próximo ao metrô"],
    imagem: "/placeholder.svg?height=300&width=400",
    galeria: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: 4,
    titulo: "Cobertura Duplex",
    preco: 850000,
    tipo: "apartamento",
    transacao: "venda",
    cidade: "Rio de Janeiro",
    bairro: "Copacabana",
    quartos: 4,
    banheiros: 3,
    area: 180,
    descricao: "Cobertura duplex com vista para o mar. Terraço amplo e acabamento de primeira qualidade.",
    caracteristicas: ["Vista para o mar", "Terraço", "Piscina privativa", "Churrasqueira", "Garagem"],
    imagem: "/placeholder.svg?height=300&width=400",
    galeria: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: 5,
    titulo: "Sala Comercial",
    preco: 3500,
    tipo: "comercial",
    transacao: "aluguel",
    cidade: "São Paulo",
    bairro: "Faria Lima",
    quartos: 0,
    banheiros: 2,
    area: 95,
    descricao: "Sala comercial em prédio corporativo na Faria Lima. Ideal para escritórios e consultorias.",
    caracteristicas: ["Ar condicionado central", "Recepção", "Segurança 24h", "Estacionamento", "Próximo ao metrô"],
    imagem: "/placeholder.svg?height=300&width=400",
    galeria: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: 6,
    titulo: "Casa de Campo",
    preco: 4200,
    tipo: "casa",
    transacao: "aluguel",
    cidade: "Belo Horizonte",
    bairro: "Nova Lima",
    quartos: 4,
    banheiros: 3,
    area: 200,
    descricao: "Casa de campo em condomínio fechado. Ambiente tranquilo e seguro, ideal para famílias.",
    caracteristicas: ["Condomínio fechado", "Piscina", "Churrasqueira", "Jardim amplo", "Garagem para 3 carros"],
    imagem: "/placeholder.svg?height=300&width=400",
    galeria: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
]
